apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-deployment
  labels: 
    app: ecomm-app
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: ecomm
        image: akiranreddy/ecomm
        ports:
        - containerPort: 80
