apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ecomm-replicaset
  labels: 
    app: ecomm-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: ecomm
        image: ravi2krishna/webapp
        ports:
           - containerPort: 80
